name: NowTV Dropbox Update

on:
  schedule:
    - cron: '0 * * * *'   # Hər saat avtomatik run
  workflow_dispatch:       # Manual run üçün düymə

jobs:
  update_nowtv:
    runs-on: ubuntu-latest

    env:
      DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
      DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run NowTV Dropbox script
        run: python ressources/tur/nowtur_dropbox.py
