name: NOWTV Auto Update

on:
  schedule:
    # Hər 5 dəqiqəyə işləyəcək
    - cron: '*/5 * * * *'
  workflow_dispatch:  # Manual run üçün

jobs:
  update_nowtv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests dropbox

      - name: Run NOWTV Dropbox script
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        run: |
          python ressources/tur/nowtur_dropbox.py
