name: NowTV Dropbox Updater

on:
  schedule:
    # Hər 5 dəqiqədə bir işləyəcək
    - cron: '*/5 * * * *'
  workflow_dispatch: # Əl ilə də işlətmək üçün

jobs:
  update_nowtv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests dropbox

      - name: Run NowTV Dropbox script
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        run: |
          python ressources/tur/nowtur_dropbox.py
