name: Update NOWTV Dropbox

on:
  schedule:
    # hər 5 dəqiqədə çalışacaq
    - cron: "*/5 * * * *"

jobs:
  update-nowtv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests dropbox

      - name: Run script
        run: python ressources/tur/nowtur_dropbox.py
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
